version: '3.8'
services:
  pg:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5452:5432"
    volumes:
      - ./db/data:/usr/src/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
